# Generated by Django 4.2.29 on 2026-04-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmemt_leader',
            new_name='department_leader',
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('url_link', models.URLField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_meetings', to='main.profile')),
                ('participants', models.ManyToManyField(related_name='meetings', to='main.profile')),
            ],
        ),
    ]
