# Generated by Django 4.2.29 on 2026-04-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_department_profile_manager_profile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
    ]
